# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.21.4-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.21.4-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/e5-2690/builds/Voronoi-Diagram-of-Spheres

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/e5-2690/builds/Voronoi-Diagram-of-Spheres

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.21.4-linux-x86_64/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.21.4-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/e5-2690/builds/Voronoi-Diagram-of-Spheres/CMakeFiles /home/e5-2690/builds/Voronoi-Diagram-of-Spheres//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/e5-2690/builds/Voronoi-Diagram-of-Spheres/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vdos

# Build rule for target.
vdos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vdos
.PHONY : vdos

# fast build rule for target.
vdos/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/build
.PHONY : vdos/fast

#=============================================================================
# Target rules for targets named CGAL_Qt5_moc_and_resources

# Build rule for target.
CGAL_Qt5_moc_and_resources: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CGAL_Qt5_moc_and_resources
.PHONY : CGAL_Qt5_moc_and_resources

# fast build rule for target.
CGAL_Qt5_moc_and_resources/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build
.PHONY : CGAL_Qt5_moc_and_resources/fast

#=============================================================================
# Target rules for targets named CGAL_Qt5_moc_and_resources_autogen

# Build rule for target.
CGAL_Qt5_moc_and_resources_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CGAL_Qt5_moc_and_resources_autogen
.PHONY : CGAL_Qt5_moc_and_resources_autogen

# fast build rule for target.
CGAL_Qt5_moc_and_resources_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources_autogen.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources_autogen.dir/build
.PHONY : CGAL_Qt5_moc_and_resources_autogen/fast

CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.o: CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.o

# target to build an object file
CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.o

CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.i: CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.i

# target to preprocess a source file
CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.i

CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.s: CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.s

# target to generate assembly for a file
CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s
.PHONY : CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.cpp.s

qrc_CGAL.o: qrc_CGAL.cpp.o
.PHONY : qrc_CGAL.o

# target to build an object file
qrc_CGAL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_CGAL.cpp.o
.PHONY : qrc_CGAL.cpp.o

qrc_CGAL.i: qrc_CGAL.cpp.i
.PHONY : qrc_CGAL.i

# target to preprocess a source file
qrc_CGAL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_CGAL.cpp.i
.PHONY : qrc_CGAL.cpp.i

qrc_CGAL.s: qrc_CGAL.cpp.s
.PHONY : qrc_CGAL.s

# target to generate assembly for a file
qrc_CGAL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_CGAL.cpp.s
.PHONY : qrc_CGAL.cpp.s

qrc_File.o: qrc_File.cpp.o
.PHONY : qrc_File.o

# target to build an object file
qrc_File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_File.cpp.o
.PHONY : qrc_File.cpp.o

qrc_File.i: qrc_File.cpp.i
.PHONY : qrc_File.i

# target to preprocess a source file
qrc_File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_File.cpp.i
.PHONY : qrc_File.cpp.i

qrc_File.s: qrc_File.cpp.s
.PHONY : qrc_File.s

# target to generate assembly for a file
qrc_File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_File.cpp.s
.PHONY : qrc_File.cpp.s

qrc_Input.o: qrc_Input.cpp.o
.PHONY : qrc_Input.o

# target to build an object file
qrc_Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Input.cpp.o
.PHONY : qrc_Input.cpp.o

qrc_Input.i: qrc_Input.cpp.i
.PHONY : qrc_Input.i

# target to preprocess a source file
qrc_Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Input.cpp.i
.PHONY : qrc_Input.cpp.i

qrc_Input.s: qrc_Input.cpp.s
.PHONY : qrc_Input.s

# target to generate assembly for a file
qrc_Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Input.cpp.s
.PHONY : qrc_Input.cpp.s

qrc_Triangulation_2.o: qrc_Triangulation_2.cpp.o
.PHONY : qrc_Triangulation_2.o

# target to build an object file
qrc_Triangulation_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Triangulation_2.cpp.o
.PHONY : qrc_Triangulation_2.cpp.o

qrc_Triangulation_2.i: qrc_Triangulation_2.cpp.i
.PHONY : qrc_Triangulation_2.i

# target to preprocess a source file
qrc_Triangulation_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Triangulation_2.cpp.i
.PHONY : qrc_Triangulation_2.cpp.i

qrc_Triangulation_2.s: qrc_Triangulation_2.cpp.s
.PHONY : qrc_Triangulation_2.s

# target to generate assembly for a file
qrc_Triangulation_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGAL_Qt5_moc_and_resources.dir/build.make CMakeFiles/CGAL_Qt5_moc_and_resources.dir/qrc_Triangulation_2.cpp.s
.PHONY : qrc_Triangulation_2.cpp.s

src/awVd_ray.o: src/awVd_ray.cpp.o
.PHONY : src/awVd_ray.o

# target to build an object file
src/awVd_ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/awVd_ray.cpp.o
.PHONY : src/awVd_ray.cpp.o

src/awVd_ray.i: src/awVd_ray.cpp.i
.PHONY : src/awVd_ray.i

# target to preprocess a source file
src/awVd_ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/awVd_ray.cpp.i
.PHONY : src/awVd_ray.cpp.i

src/awVd_ray.s: src/awVd_ray.cpp.s
.PHONY : src/awVd_ray.s

# target to generate assembly for a file
src/awVd_ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/awVd_ray.cpp.s
.PHONY : src/awVd_ray.cpp.s

src/bfs_for_vert.o: src/bfs_for_vert.cpp.o
.PHONY : src/bfs_for_vert.o

# target to build an object file
src/bfs_for_vert.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/bfs_for_vert.cpp.o
.PHONY : src/bfs_for_vert.cpp.o

src/bfs_for_vert.i: src/bfs_for_vert.cpp.i
.PHONY : src/bfs_for_vert.i

# target to preprocess a source file
src/bfs_for_vert.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/bfs_for_vert.cpp.i
.PHONY : src/bfs_for_vert.cpp.i

src/bfs_for_vert.s: src/bfs_for_vert.cpp.s
.PHONY : src/bfs_for_vert.s

# target to generate assembly for a file
src/bfs_for_vert.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/bfs_for_vert.cpp.s
.PHONY : src/bfs_for_vert.cpp.s

src/compute_bisectors.o: src/compute_bisectors.cpp.o
.PHONY : src/compute_bisectors.o

# target to build an object file
src/compute_bisectors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/compute_bisectors.cpp.o
.PHONY : src/compute_bisectors.cpp.o

src/compute_bisectors.i: src/compute_bisectors.cpp.i
.PHONY : src/compute_bisectors.i

# target to preprocess a source file
src/compute_bisectors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/compute_bisectors.cpp.i
.PHONY : src/compute_bisectors.cpp.i

src/compute_bisectors.s: src/compute_bisectors.cpp.s
.PHONY : src/compute_bisectors.s

# target to generate assembly for a file
src/compute_bisectors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/compute_bisectors.cpp.s
.PHONY : src/compute_bisectors.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/power.o: src/power.cpp.o
.PHONY : src/power.o

# target to build an object file
src/power.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/power.cpp.o
.PHONY : src/power.cpp.o

src/power.i: src/power.cpp.i
.PHONY : src/power.i

# target to preprocess a source file
src/power.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/power.cpp.i
.PHONY : src/power.cpp.i

src/power.s: src/power.cpp.s
.PHONY : src/power.s

# target to generate assembly for a file
src/power.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/power.cpp.s
.PHONY : src/power.cpp.s

src/ray_intersections.o: src/ray_intersections.cpp.o
.PHONY : src/ray_intersections.o

# target to build an object file
src/ray_intersections.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/ray_intersections.cpp.o
.PHONY : src/ray_intersections.cpp.o

src/ray_intersections.i: src/ray_intersections.cpp.i
.PHONY : src/ray_intersections.i

# target to preprocess a source file
src/ray_intersections.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/ray_intersections.cpp.i
.PHONY : src/ray_intersections.cpp.i

src/ray_intersections.s: src/ray_intersections.cpp.s
.PHONY : src/ray_intersections.s

# target to generate assembly for a file
src/ray_intersections.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/ray_intersections.cpp.s
.PHONY : src/ray_intersections.cpp.s

src/voronoi_mesh_details.o: src/voronoi_mesh_details.cpp.o
.PHONY : src/voronoi_mesh_details.o

# target to build an object file
src/voronoi_mesh_details.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/voronoi_mesh_details.cpp.o
.PHONY : src/voronoi_mesh_details.cpp.o

src/voronoi_mesh_details.i: src/voronoi_mesh_details.cpp.i
.PHONY : src/voronoi_mesh_details.i

# target to preprocess a source file
src/voronoi_mesh_details.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/voronoi_mesh_details.cpp.i
.PHONY : src/voronoi_mesh_details.cpp.i

src/voronoi_mesh_details.s: src/voronoi_mesh_details.cpp.s
.PHONY : src/voronoi_mesh_details.s

# target to generate assembly for a file
src/voronoi_mesh_details.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vdos.dir/build.make CMakeFiles/vdos.dir/src/voronoi_mesh_details.cpp.s
.PHONY : src/voronoi_mesh_details.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CGAL_Qt5_moc_and_resources_autogen"
	@echo "... CGAL_Qt5_moc_and_resources"
	@echo "... vdos"
	@echo "... CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.o"
	@echo "... CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.i"
	@echo "... CGAL_Qt5_moc_and_resources_autogen/mocs_compilation.s"
	@echo "... qrc_CGAL.o"
	@echo "... qrc_CGAL.i"
	@echo "... qrc_CGAL.s"
	@echo "... qrc_File.o"
	@echo "... qrc_File.i"
	@echo "... qrc_File.s"
	@echo "... qrc_Input.o"
	@echo "... qrc_Input.i"
	@echo "... qrc_Input.s"
	@echo "... qrc_Triangulation_2.o"
	@echo "... qrc_Triangulation_2.i"
	@echo "... qrc_Triangulation_2.s"
	@echo "... src/awVd_ray.o"
	@echo "... src/awVd_ray.i"
	@echo "... src/awVd_ray.s"
	@echo "... src/bfs_for_vert.o"
	@echo "... src/bfs_for_vert.i"
	@echo "... src/bfs_for_vert.s"
	@echo "... src/compute_bisectors.o"
	@echo "... src/compute_bisectors.i"
	@echo "... src/compute_bisectors.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/power.o"
	@echo "... src/power.i"
	@echo "... src/power.s"
	@echo "... src/ray_intersections.o"
	@echo "... src/ray_intersections.i"
	@echo "... src/ray_intersections.s"
	@echo "... src/voronoi_mesh_details.o"
	@echo "... src/voronoi_mesh_details.i"
	@echo "... src/voronoi_mesh_details.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

